### PR TITLE
Use yarn against npm- not both. Generate typings instead of manually typed

### PR DESCRIPTION
**Pull request by FDiskas**
I can help you make it automatic with github actions. Also probably it's a good idea to grab icons from [original source](https://github.com/feathericons/feather/tree/master/icons) instead of holding them in the repository. So in case any new icons will be added it will appear here with a new release. So we would need some sort of automation script.

Noticed that you have `package-lock.json` and `yarn.lock` - this is not good it can mess tup things. You need to decide which package manager you want to use. You can't have them both.

Regarding releases I can provide a prove of concept on how it can be done.

Regarding this PR - I tested generated typings and thous that you added by hand - they works exactly the same - any reason they not worked in your case?

### CODE REVIEW

**Comment by yigithanyucedag** [comment]
Hi, thank you very much for your contribution. The idea of automatically pulling the icons from the original source makes sense, but I've never used GitHub actions before. And you're right I only need to use one package manager while creating the repo I guess something went wrong and I used both. Would it be enough to delete yarn.lock just to use npm? Since you said in the previous pr that handwriting types would be better, I created it myself, but if there is no difference, we can continue with the method you suggested.

**Comment by FDiskas** [comment]
Ok I can update PR to use npm instead yarn. Also I can create another PR to use github actions for releasing package without using npm publish. Also will try to explain how it will work.

Can you also enable discussions in this repository so we could discuss about the flow?

**Comment by yigithanyucedag** [comment]
I activated the discussion page and merged the commits into master 👍🏻  Should I release a new version now?

**Comment by FDiskas** [comment]
In case you release - I could check this on real project

**Pull request merged**
