### PR TITLE
Optimise action

### PR DESCRIPTION
**Pull request by FDiskas**
Remove unneeded build step the main action does the same and in case of any error it will just stop

### CODE REVIEW

**Comment by FDiskas** [comment]
And create releases only using github, not npm by it self.

**Comment by yigithanyucedag** [comment]
I updated the version in package.json then I created a release on github then but in actions there is an error occured. 

"npm ERR! Version not changed, might want --allow-same-version"

**Comment by FDiskas** [comment]
No do not touch package.json
Just use github release and fill up version here with `v` prefix
image

**Comment by yigithanyucedag** [comment]
Oh ok. Is there any way to sync this action with package.json? Maybe this? https://stackoverflow.com/a/54371474

**Comment by FDiskas** [comment]
I tried and did not managed to do so. In that case some sort of credentials to github is needed, and refs - i could not manage that. maybe there is some github action already predefined todo that but I would not go that way. May be later I will find some and I will create a PR

**Comment by FDiskas** [comment]
@yigithanyucedag regarding semantic release plugin. The main difference is that the release will be triggered on master branch every time when something is pushed to that branch. The release notes are generated from commit messages and thous messages must be in specific format like `fix: something`

So in other words there will be no manual work or manual trigger of a release.
In case you want that any way there is what you need.

> p.s. package.json also not updates automatically.

```yml
name: Publish Package

on:
  push:
    branches:
      - "main"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          always-auth: true
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: akhilmhdh/contributors-readme-action@v2.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Pull request merged**
