### PR TITLE
Dont be scary

### PR DESCRIPTION
**Pull request by FDiskas**
That needs to be deeply tested.
You can test this out by running
1. `npm ci`
2. `npm run prepublish`

That suppose to do the following:
1. fetch git submodule
2. convert icons to react-native icons (typescript version)
3. convert ts to js and add typings
4. convert all vanilla typings to single file

all new generated content will be available at lib directory and this suppose to be published

### CODE REVIEW

**Comment by FDiskas** [comment]
I would also like to remove icons from src directory - they are fetched automatically any way.

**Comment by yigithanyucedag** [comment]
I removed icons folder. I run the prepublish script and it created all the icons under the lib folder but why did you add lib/ path to .gitignore?

**Comment by FDiskas** [comment]
As far as i know files will be published any way? Or I'm wrong? You can test that by runing `npm pack`

**Comment by yigithanyucedag** [comment]
Yes you are right. I released the new version. Thanks for your big contribution!

**Comment by FDiskas** [comment]
It was interesting experience. Thanks for letting me to mess a raund.

Now repository code looks strange :)

**Pull request merged**
